theme: jekyll-theme-dinky
title: Jake Robie
description: Senior at George Mason University<br><br>Co-op at Battelle Memorial Institute
show_downloads: false
Author: Jake Robie
author_email: Jacob.Robie@gmail.com
linkedin_username: robiej